CREATE SEQUENCE SEQ_ID_ITEM_NOTA START 1;

CREATE TABLE NOTA_FISCAL_ELETRONICA(
	ID SERIAL PRIMARY KEY,
	NUMERO_NOTA BIGINT,
	DATA_EMISSAO DATE,
	EMINENTE VARCHAR(500),
	DESTINATARIO VARCHAR(500),
	VALOR_TOTAL DOUBLE PRECISION
);    
 
CREATE TABLE ITENS_ENTRADA_NOTA_FISCAL(
	ID_NOTA_FISCAL INTEGER,
	CODIGO_PRODUTO INTEGER, 
	ID_UNIDADE_MEDIDA INTEGER,
	QUANTIDADE DOUBLE PRECISION, 
	VALOR_UNITARIO DOUBLE PRECISION
); 

ALTER TABLE ITENS_ENTRADA_NOTA_FISCAL ADD CONSTRAINT fk_nota_fiscal_itens
FOREIGN KEY (ID_NOTA_FISCAL) REFERENCES NOTA_FISCAL_ELETRONICA (ID);   
 
ALTER TABLE ITENS_ENTRADA_NOTA_FISCAL ADD CONSTRAINT fk_iten_entrada_nf
FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTOS (ID);

ALTER TABLE ITENS_ENTRADA_NOTA_FISCAL ADD CONSTRAINT fk_un_medida_entrada_nf
FOREIGN KEY (ID_UNIDADE_MEDIDA) REFERENCES UNIDADES_DE_MEDIDA (ID);